#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

npx tsc
npm run lint

# Temporarily disabling this, as these tests are using real application
# and IMO should be run on pipeline, not on each commit

# npm run test
